version: "3.9"
services: 
  nginx:
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    depends_on:
      - api 
      - client
    ports:
      - "8080:80"

  client:
    build: 
      dockerfile: Dockerfile.dev
      context: ./client
    volumes: 
      - /app/node_modules
      - ./client:/app
    stdin_open: true

  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes: 
      - /app/node_modules
      - ./server:/app
    environment: 
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=mysql_password
      - MYSQL_DB=AtmosphereDB
    depends_on: 
      - mysql
      
  mysql:
    image: "mysql:latest"
    restart: always
    environment: 
      - MYSQL_ROOT_PASSWORD=mysql_password
    cap_add:
      - SYS_NICE
